Project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TestingService.urls'))
]

TestingService/urls.py
from django.urls import path

from .views import *

app_name = 'TestingService'
urlpatterns = [
    path('', main, name='main'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('question_set_list/', QuestionSetList.as_view(), name='question_set_list'),
    path('question_set_list/<int:pk>/', testing_question, name='test'),
    path('question_set_list/<int:pk>/answer/', testing_answers, name='testing_answers'),
    path('question_set_list/<int:pk>/result_test/', result_test, name='result_test'),

]

TestingService/models.py
from django.db import models

from django.urls import reverse


class Questions(models.Model):
    text_question = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Questions'
        verbose_name_plural = 'Questions'

    def __str__(self):
        return str(self.text_question)


class Choices(models.Model):
    question_number = models.ForeignKey(Questions, on_delete=models.CASCADE)
    choice = models.CharField(max_length=200)
    flag_choice = models.BooleanField()

    class Meta:
        verbose_name = 'Choices'
        verbose_name_plural = 'Choices'

    def __str__(self):
        return str(self.choice)


class QuestionsSet(models.Model):

    set_title = models.TextField()
    questions = models.ManyToManyField(Questions)

    class Meta:
        verbose_name = 'QuestionsSets'
        verbose_name_plural = 'QuestionsSets'

    def __str__(self):
        return self.set_title

    def get_absolute_url(self):
        return reverse('TestingService:question_set_list')

TestingService/forms.py
from django import forms
from .models import *


class QuestionSetForm(forms.Form):
    question = forms.CharField(
        max_length=500,
        label='Вопрос ',
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 30, 'readonly': True})
    )
    answers = forms.ModelMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple(),
        label='Варианты ответа'
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['answers'].queryset = kwargs['data']['answers']

TestingService/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect

import matplotlib.pyplot as plt
import io
import base64

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from TestingService.forms import QuestionSetForm
from TestingService.models import QuestionsSet, Questions, Choices


def main(request):
    return render(request, 'TestingService/base.html')


def logout_view(request):
    logout(request)
    return render(request, 'TestingService/base.html')


def testing_question(request, pk):
    """
    Outputting one test question
    """
    request.session.set_expiry(value=0)
    index = request.session.get("current_question", 0)
    q_set = Questions.objects.filter(questionsset__id=pk)
    q_number = q_set.count()
    question = q_set[index]
    answers = Choices.objects.filter(question_number=question.id)
    request.session['right_answers'] = [ans.choice for ans in
                                        Choices.objects.filter(question_number=question.id, flag_choice=1)]
    request.session['q_number'] = q_number
    data = {'question': question, 'answers': answers}
    form = QuestionSetForm(data=data)
    return render(request, 'TestingService/test_questions.html',
                  {'form': form, 'pk': pk, 'error_message': request.session.get('error_message', None)})


def testing_answers(request, pk):
    """
    Checking answers of one test question
    """
    request.session['error_message'] = ""
    checked_answers = request.POST.getlist('checked_ans')
    if not checked_answers:
        request.session['error_message'] = "Не выбран ни один вариант ответа"
        return redirect("TestingService:test", pk)
    index = request.session.get("current_question", 0)
    result = request.session.get("current_result", 0)
    right_answers = request.session['right_answers']
    if checked_answers == right_answers:
        request.session["current_result"] = result + 1

    index += 1
    if index < request.session['q_number']:
        request.session["current_question"] = index
        return redirect("TestingService:test", pk)
    else:
        return redirect("TestingService:result_test", pk)


def result_test(request, pk):
    """
    Building a pie chart and stream creating for picture
    :return: picture with results of test
    """
    num = request.session.get('q_number')
    res = request.session.get("current_result")
    res = int(res)
    wrong_answers = num - res
    values = [res, wrong_answers]
    labels = ['Правильно', 'Неправильно']
    colors = ['green', 'red']
    figure = plt.figure()
    plt.pie(values, labels=labels, autopct='%1.2f%%', colors=colors, startangle=90)
    # creating a stream to draw a pie chart
    stream = io.BytesIO()
    plt.savefig(stream, format='png')
    del figure
    b64str = base64.b64encode(stream.getvalue()).decode()
    data = {'res': res, 'num': num, 'b64str': b64str}
    return render(request, 'TestingService/result.html', data)


class QuestionSetList(LoginRequiredMixin, ListView):
    """
    Displays list of the tests (question sets) after login
    """
    model = QuestionsSet
    queryset = QuestionsSet.objects.all()
    login_url = '/login/'
    template_name = 'TestingService/question_set_list.html'


class LoginUser(LoginView):
    """
    Login existing users
    """
    template_name = 'TestingService/login.html'
    form_class = AuthenticationForm

    def get_success_url(self):
        return reverse_lazy('TestingService:question_set_list')


class RegisterUserView(CreateView):
    """
    Registration new users
    """
    form_class = UserCreationForm
    template_name = 'TestingService/register.html'
    success_url = reverse_lazy('TestingService:login')

TestingService/templates/TestingService/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TestingService</title>
    <link rel=stylesheet href={% static "TestingService/css/app.css" %}>
</head>
<body>

{% block title01 %}
    <aside>
        <h2>Testing Service</h2><br>
        <ul.hr>
            <li><a href="{% url 'TestingService:register' %}">Register</a></li><br>
            <li><a href="{% url 'TestingService:login' %}">Login</a></li><br>
            <li><a href="{% url 'TestingService:logout' %}">Logout</a></li><br>
            <li><a href="{% url 'TestingService:main' %}">Home</a></li><br>
        </ul.hr>
    </aside>
{% endblock title01 %}

{% block content %}
    <br>
    <li><a href="{% url 'TestingService:question_set_list' %}">Choose the test</a></li><br>
{% endblock content %}

{% block content01 %}

{% endblock content01 %}

</body>
</html>

TestingService/templates/TestingService/login.html
{% extends 'TestingService/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <p><input type="submit" value="Log_in"></p>
</form>
{% endblock content %}

TestingService/templates/TestingService/question_set_list.html
{% extends 'TestingService/base.html' %}

{% block content %}
    _________________________________
    {{ request.user }}
    {% for q_set in object_list %}
        <li><a href="{{ q_set.pk }}">{{ q_set }}</a></li>
    {% endfor %}
{% endblock content %}

TestingService/templates/TestingService/register.html
{% extends 'TestingService/base.html' %}


{% block content %}
    <form method = 'post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
    </form>

{% endblock content %}

TestingService/templates/TestingService/result.html
{% extends 'TestingService/base.html' %}

{% block content %}
    <img src="data:image/png;base64, {{ b64str }}" alt="Your results" />
Ура! Тест пройден! <br>
    Ваш результат {{ res }} из {{ num }}
{% endblock content %}

TestingService/templates/TestingService/test_questions.html
{% extends 'TestingService/base.html' %}
{% block content %}
    {% if error_message %}
        <p style="color:red">{{ error_message }}</p>
    {% endif %}
    <form action="{% url 'TestingService:testing_answers' pk %}" method="post">
        {% csrf_token %}
        <p><label for="id_question">Вопрос : </label><textarea name="question" cols="30" rows="3" readonly
                                                               maxlength="500"
                                                               required>{{ form.data.question }}</textarea></p>
        <p><label>Варианты ответа :</label>
            {% for ans in form.data.answers %}
                <li><label><input type="checkbox" name="checked_ans" value="{{ ans.choice }}">{{ ans.choice }}</label>
                </li>
            {% endfor %}
        <br><input type="submit" value="Ответить"></br>
    </form>
{% endblock content %}

{% comment %}
{% block content %}
        <form action="{% url 'TestingService:testing_answers' pk %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Ответить">
        </form>
{% endblock content %}
{% endcomment %}